### ISSUE TITLE
Would be nice to specify a folder and nothing else, and glob match all the gifs.

### ISSUE THREAD

**Issue by lewiscowper** [sole/catserver#2]
I'm going to take a look at this tonight, but it'd be awesome if the images array could auto-build with [glob](https://www.npmjs.com/package/glob).

I basically want to create a redpanda server, but would have to manually specify gif names. It'd also make extending this easier.

**Comment by sole** [comment]
I see where you're going but I believe you sadly can't enumerate the contents of the folder like you could with node.js :-/

Shall we ask around?

**Comment by lewiscowper** [comment]
Ah, okay, I don't really get the whole browserify magic thing, and thought that might be pulling npm packages into the browser. It'd be cool to have though, it's a really good workflow.
